export const otModel = {
  name: 'ot',
  fields: [
    'id',
    'cliente',
    'direccion',
    'comuna',
    'contactoTerreno',
    'telefonoContacto',
    'clienteRelacionado',
    'vehiculoRelacionado',
    'tipoServicio',
    'subtipoServicio',
    'tecnicoAsignado',
    'estado',
    'fecha',
    'hora',
    'observaciones',
    'resumenTrabajo',
    'recomendaciones',
    'creadoEn',
    'cerradoEn',
    'createdAt',
    'updatedAt',
    'creadoPor',
    'actualizadoPor',
    /** manual | automatic — control operativo (Jarvis puede sugerir / ejecutar en automático) */
    'operationMode',
    /** Origen del pedido: whatsapp, correo, llamada, manual, jarvis, etc. */
    'origenPedido',
    /** Quien asignó el técnico actual (Romina, Gery, Jarvis, sistema) */
    'asignadoPor',
    /** Responsable operativo actual (suele coincidir con técnico en terreno) */
    'responsableActual',
    'historial',
    'costoMateriales',
    'costoManoObra',
    'costoTraslado',
    'costoOtros',
    'costoTotal',
    'montoCobrado',
    'utilidad',
    'pdfName',
    'pdfUrl',
    'equipos',
    'fotografiasAntes',
    'fotografiasDurante',
    'fotografiasDespues',
  ],
  statusOptions: ['pendiente', 'en proceso', 'terminado'],
  operationModes: ['manual', 'automatic'],
  serviceTypes: ['clima', 'flota'],
  equipoEstadoOptions: ['operativo', 'mantenimiento', 'falla'],
  maxEquipos: 12,
};
