export const otModel = {
  name: 'ot',
  fields: [
    'id',
    'cliente',
    'direccion',
    'comuna',
    'contactoTerreno',
    'telefonoContacto',
    'clienteRelacionado',
    'vehiculoRelacionado',
    'tipoServicio',
    'subtipoServicio',
    'tecnicoAsignado',
    'estado',
    'fecha',
    'hora',
    'observaciones',
    'resumenTrabajo',
    'recomendaciones',
    'fotografiasAntes',
    'fotografiasDurante',
    'fotografiasDespues',
  ],
  statusOptions: ['pendiente', 'en proceso', 'terminado'],
  serviceTypes: ['clima', 'flota'],
};
