export const solicitudFlotaModel = {
  name: 'solicitudFlota',
  fields: [
    'id',
    'cliente',
    'tipoServicio',
    'fecha',
    'hora',
    'origen',
    'destino',
    'conductor',
    'vehiculo',
    'estado',
    'detalle',
    'responsable',
    'observacion',
    'observacionCierre',
    'costoCombustible',
    'costoPeaje',
    'costoChofer',
    'costoExterno',
    'materiales',
    'manoObra',
    'costoTraslado',
    'otros',
    'costoTotal',
    'ingresoEstimado',
    'ingresoFinal',
    'montoCobrado',
    'utilidad',
    'monto',
    'createdAt',
    'updatedAt',
    'historial',
  ],
  tipoServicioOptions: ['traslado', 'asistencia', 'otro'],
  estados: [
    'recibida',
    'evaluacion',
    'cotizada',
    'aprobada',
    'programada',
    'en_ruta',
    'completada',
    'cerrada',
  ],
};
