import {
  getMaestroConductores,
  getMaestroContactos,
  getMaestroDocumentoDescarga,
  getMaestroDocumentos,
  getMaestroTecnicos,
  getMaestroVehiculos,
  patchMaestroConductor,
  patchMaestroContacto,
  patchMaestroDocumento,
  postMaestroDocumentoAprobar,
  patchMaestroTecnico,
  patchMaestroVehiculo,
  postMaestroConductor,
  postMaestroContacto,
  postMaestroDocumentosIngesta,
  postMaestroDocumentosRepararVinculos,
  postMaestroDocumentoCrearEntidad,
  postMaestroDocumentoReclasificar,
  postMaestroTecnico,
  postMaestroVehiculo,
} from '../controllers/maestro.controller.js';

export const maestroRoutes = [
  { method: 'GET', path: '/maestro/contactos', handler: getMaestroContactos },
  { method: 'POST', path: '/maestro/contactos', handler: postMaestroContacto },
  { method: 'PATCH', path: '/maestro/contactos/:id', handler: patchMaestroContacto },
  { method: 'GET', path: '/maestro/tecnicos', handler: getMaestroTecnicos },
  { method: 'POST', path: '/maestro/tecnicos', handler: postMaestroTecnico },
  { method: 'PATCH', path: '/maestro/tecnicos/:id', handler: patchMaestroTecnico },
  { method: 'GET', path: '/maestro/conductores', handler: getMaestroConductores },
  { method: 'POST', path: '/maestro/conductores', handler: postMaestroConductor },
  { method: 'PATCH', path: '/maestro/conductores/:id', handler: patchMaestroConductor },
  { method: 'GET', path: '/maestro/vehiculos', handler: getMaestroVehiculos },
  { method: 'POST', path: '/maestro/vehiculos', handler: postMaestroVehiculo },
  { method: 'PATCH', path: '/maestro/vehiculos/:id', handler: patchMaestroVehiculo },
  { method: 'GET', path: '/maestro/documentos', handler: getMaestroDocumentos },
  { method: 'POST', path: '/maestro/documentos/ingesta', handler: postMaestroDocumentosIngesta },
  { method: 'POST', path: '/maestro/documentos/reparar-vinculos', handler: postMaestroDocumentosRepararVinculos },
  { method: 'PATCH', path: '/maestro/documentos/:id', handler: patchMaestroDocumento },
  { method: 'POST', path: '/maestro/documentos/:id/aprobar', handler: postMaestroDocumentoAprobar },
  { method: 'POST', path: '/maestro/documentos/:id/crear-entidad', handler: postMaestroDocumentoCrearEntidad },
  { method: 'POST', path: '/maestro/documentos/:id/reclasificar', handler: postMaestroDocumentoReclasificar },
  { method: 'GET', path: '/maestro/documentos/:id/descarga', handler: getMaestroDocumentoDescarga },
];
